export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET";
export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";
export const CHANGE_BASKET_COUNT_PRODUCTS = "CHANGE_BASKET_COUNT_PRODUCTS";
export const TOGGLE_MENU = "TOGGLE_MENU";
